### ISSUE TITLE
Several issues regarding fine-tune

### ISSUE THREAD

**Issue by chauncygu** [GreenBitAI/green-bit-llm#22]
There are several issues when I use the code to fine-tune llama3, 
like
`from bitorch_engine.optim import DiodeMix
ModuleNotFoundError: No module named 'bitorch_engine'`

and which version of trl do you support?

**Comment by Jopyth** [comment]
In my last test installation I used `trl==0.9.4`. If we discover incompatibilities with future version we are going to note them, please let us know if you have a problem with them.

The installation of bitorch engine is described in the first paragraph of the installation instructions, please follow that link to install bitorch engine. 
> We support several ways to install this package. Except for the docker method, you should first install [Bitorch Engine](https://github.com/GreenBitAI/bitorch-engine) according to the [official instructions](https://github.com/GreenBitAI/bitorch-engine?tab=readme-ov-file#installation).

Since the instructions are expected to change frequently due to our efforts of providing more compatible binary packages, we only linked to them and did not copy them over. We are however going to improve the instructions to make this step less likely to be missed.
