### ISSUE TITLE
thanks for this modules

### ISSUE THREAD

**Issue by NickyDark1** [GreenBitAI/green-bit-llm#8]
is posible example google colab?

thanks

**Comment by Jopyth** [comment]
Since google colab supports running any command with `!`, e.g. `!pip install ...`, it should be possible. Unfortunately, we do have a working google colab environment yet. If there is a strong interest, we could create an example.

To install this package it would be required to build bitorch engine (probably through such custom commands) in the environment. Then everything else should work.

We are planning to provide binary releases for bitorch engine, then it would become much easier to setup/install in environment such as colab through pip.
